markdown: rdiscount
pygments: true
auto: true
baseurl: /Cake-Resque

navigation:
- text: Home
  url: /
- text: Install
  url: /install
- text: Changelog
  url: /changelog

name: CakeResque

include:
- .htaccess