server: true
markdown: rdiscount
pygments: true
lsi: true
auto: true
baseurl: /Cake-Resque

navigation:
- text: Home
  url: /
- text: Install
  url: /install
- text: Changelog
  url: /changelog

name: CakeResque
permalink: /:title

include:
- .htaccess